### ISSUE TITLE
屏蔽方式有点太暴力

### ISSUE THREAD

**Issue by Logic530** [sayomelu/NothingBlock#3]
屏蔽方式就是屏蔽主页下面的分区咯
购物网站还行，因为基本上都是靠搜索框买东西
但B站只留了个番剧分区似乎太暴力了，毕竟有时候还是要靠B站分区推荐找视频看的

**Comment by sayomelu** [comment]
You can enter sections via the bar above.
<img width="1203" alt="screen shot 2019-01-19 at 23 05 24" src="https://user-images.githubusercontent.com/16492117/51428456-c6c72200-1c3e-11e9-866a-3bb78b38af72.png">

If you have a better solution, you can suggest it！ 😊

**Comment by sayomelu** [comment]
You can enter sections via the bar above.
![screen shot 2019-01-19 at 23 05 24](https://user-images.githubusercontent.com/16492117/51428506-861bd880-1c3f-11e9-8a19-976b44cf0cc9.jpg)

If you have a better solution, you can suggest it！ 😊
